### ISSUE TITLE
its says missing dependency mkvmerge

### ISSUE THREAD

**Issue by nammminn2** [Bananaman/BananaScripts#1]
when I tired to extract the subs

**Comment by Arcitec** [comment]
@nammminn2 Oops, I forgot to mention (in the source code) that it requires the [MKVToolNix](https://mkvtoolnix.download/) programs.

If you're on Linux, it's usually handled by your distribution and is a simple matter to install via your package manager or software center. On my Fedora desktop, I just opened the "Software" app, searched for it, and installed it with one click.

If you're on Mac, you should install it via [Homebrew](https://brew.sh/) to get it added to your system's path/environment properly.

And last and least, if you're on Windows, you should install Chocolatey and then use it to install [this package](https://community.chocolatey.org/packages/mkvtoolnix). Chocolatey usually takes care of adding programs to your system's path/environment so that they will be found by the script. I haven't tried it on Windows so I can't say for sure, but I am almost certain that it will be added to the path automatically. Edit: Yes, Chocolatey on Windows adds it to the PATH automatically, but you need to reboot the computer after installing mkvtoolnix, for the tools to be detectable.

After that's installed, and is in your system's path (meaning it's found if you try to run "mkvmerge" or similar tools in a command line window), then the subtitle script will work. Good luck! :)
